### PR TITLE
Update to Laravel 11

### PR DESCRIPTION
**Pull request by mbanusic**
Update to Laravel 11

### CODE REVIEW

**Comment by ArthurPatriot** [comment]
Looks like your changes drop Laravel 10 support

**Comment by ArthurPatriot** [comment]
@QuentinGab laravel 11 support will be ready today. Let me 2 hours.

**Comment by ArthurPatriot** [comment]
@QuentinGab update here - https://github.com/kalynasolutions/laravel-tus/pull/20

**Comment by QuentinGab** [comment]
> @QuentinGab update here - #20

Great news ! 

Thank you very much for the reactivity

**Pull request closed without merging**
